name: Run Tests on PRs

on:
  pull_request:
    branches:
      - main  # adjust if your main branch has a different name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # change to your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run coverage
